import type { Metadata } from "next";
import Link from "next/link";
const demoContract="0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4";
export const metadata:Metadata={alternates:{canonical:"/"}};
const faq=[
  ["Does a high score mean I should buy?","No. The score summarizes available evidence. BaseLens does not predict returns or tell you what to buy."],
  ["What happens when data is missing?","Missing evidence lowers confidence. It is kept separate from a risk that was actually detected."],
  ["What does BaseLens actually score?","Market health, liquidity, trading activity, holder distribution, contract safety and momentum."],
  ["Can I share or save an analysis?","Yes. Token research has a share-link control and a print view that can be saved as a PDF."],
  ["Which network is supported?","BaseLens currently researches ERC-20 token contracts on Base mainnet."],
] as const;
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};
export default function Home(){return <main id="main-content" className="product-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><section className="product-hero"><div className="product-grid" aria-hidden="true"/><div className="shell product-hero-inner"><div className="hero-copy"><div className="product-eyebrow"><span/> Base token research agent</div><h1>Know what you’re looking at <em>before you trade.</em></h1><p>Paste a Base token contract. BaseLens checks the market, liquidity, holders and contract risk, then explains the evidence in plain language.</p><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href={`/analyze/${demoContract}`}>Open TOSHI demo</Link></div><div className="product-proof"><span>No account</span><i/><span>No wallet</span><i/><span>Base mainnet</span></div></div><div className="hero-research-panel" aria-label="BaseLens research flow preview"><div className="hero-panel-head"><span>Research path</span><b>Evidence first</b></div><ol><li><span>01</span><div><b>Contract</b><small>Confirm token and Base deployment</small></div><i>Ready</i></li><li><span>02</span><div><b>Market</b><small>Price, liquidity, volume and pair activity</small></div><i>Live</i></li><li><span>03</span><div><b>Holders</b><small>Distribution and concentration signals</small></div><i>Check</i></li><li><span>04</span><div><b>Security</b><small>Restrictions, taxes and contract controls</small></div><i>Check</i></li><li className="agent-row"><span>05</span><div><b>Agent</b><small>Explain the strongest signal and biggest risk</small></div><i>Explain</i></li></ol><Link href={`/analyze/${demoContract}`}>View a completed analysis <span>→</span></Link></div></div></section>
<section className="product-preview-section"><div className="shell product-preview-wrap"><div className="product-preview-bar"><span>Product workspace</span><b>Missing evidence stays separate from detected risk</b></div><div className="product-preview"><aside><div className="preview-token"><div>?</div><span><b>BASE TOKEN</b><small>Research workspace</small></span></div><nav><strong>Overview</strong><span>Market</span><span>Holders</span><span>Security</span></nav><div className="preview-status"><i/> Research workflow</div></aside><div className="preview-main"><header><div><small>BASELENS SCORE</small><strong>--<span>/100</span></strong><em>Calculated from evidence</em></div><div className="preview-agent"><small>AGENT VERDICT</small><p>The agent explains the strongest signal, biggest risk and what evidence is still missing.</p></div></header><div className="preview-metrics"><div><span>Liquidity</span><b>--</b></div><div><span>Safety</span><b>--</b></div><div><span>Holders</span><b>--</b></div><div><span>Trading</span><b>--</b></div></div><div className="preview-evidence"><div><small>STRONGEST SIGNAL</small><b>Shown from collected evidence</b></div><div><small>BIGGEST RISK</small><b>Separated from missing data</b></div><div><small>CONFIDENCE</small><b>Based on evidence coverage</b></div></div></div></div></div></section>
<section className="product-story"><div className="shell story-grid"><div className="story-heading"><span>One contract. Four checks.</span><h2>Less guessing. More evidence.</h2><p>BaseLens separates measurable token data from the agent’s interpretation so you can see what the verdict is actually based on.</p></div><div className="story-list"><article><span>01</span><div><h3>Market & liquidity</h3><p>Price, market cap, liquidity, trading flow, pair age and recent volume.</p></div></article><article><span>02</span><div><h3>Holder structure</h3><p>Holder count, top-wallet concentration and distribution risk when the data is available.</p></div></article><article><span>03</span><div><h3>Contract security</h3><p>Honeypot signals, restrictions, taxes, ownership, minting and verification.</p></div></article><article><span>04</span><div><h3>Agent interpretation</h3><p>Deterministic scores first. Then the agent explains the evidence, confidence and trade-offs.</p></div></article></div></div></section>
<section className="agent-loop-section"><div className="shell agent-loop-grid"><div><span className="section-kicker">Agent workflow</span><h2>It researches before it answers.</h2><p>The model does not invent the token data. It receives normalized evidence after the checks are complete.</p></div><div className="agent-loop"><div><b>Observe</b><span>Collect evidence</span></div><i>→</i><div><b>Analyze</b><span>Normalize signals</span></div><i>→</i><div><b>Score</b><span>Calculate signals</span></div><i>→</i><div><b>Explain</b><span>Show trade-offs</span></div></div></div></section>
<section id="faq" className="faq-section"><div className="shell faq-grid"><div><span className="section-kicker">FAQ</span><h2>Before you use the score.</h2><p className="faq-intro">A few things worth knowing before you use BaseLens research in a decision.</p></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="product-final-cta"><div className="shell final-cta-inner"><div><span>BaseLens Agent</span><h2>Paste the contract.<br/>See what holds up.</h2></div><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href="/compare">Compare tokens</Link></div></div></section></main>}
