import type { Metadata } from "next";
import Link from "next/link";
const demoContract="0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4";
export const metadata:Metadata={alternates:{canonical:"/"}};
const faq=[
  ["Does a high score mean I should buy?","No. The score summarizes available evidence. BaseLens does not predict returns or tell you what to buy."],
  ["What happens when data is missing?","Missing evidence lowers confidence. It is kept separate from a risk that was actually detected."],
  ["Does BaseLens analyze X sentiment?","BaseLens only shows social evidence it can retrieve reliably. It will not invent sentiment when a source is unavailable."],
  ["Can I share or save an analysis?","Yes. Token research has a share-link control and a print view that can be saved as a PDF."],
  ["Which network is supported?","BaseLens currently researches ERC-20 token contracts on Base mainnet."],
] as const;
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};
export default function Home(){return <main id="main-content" className="product-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><div className="product-status"><i/><span>Base mainnet</span><b>Live data</b><span>Research tool</span></div><section className="product-hero"><div className="product-grid" aria-hidden="true"/><div className="shell product-hero-inner"><div className="product-eyebrow"><span/> Base mainnet token research</div><h1>Look before<br/>you <em>ape.</em></h1><p>BaseLens researches any Base token contract, with extra depth for unfamiliar and fast-moving tokens. It checks the evidence, grades the profile, and explains what still needs your attention.</p><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href={`/analyze/${demoContract}`}>Open live demo</Link></div><Link className="demo-hint" href={`/analyze/${demoContract}`}>See a completed TOSHI analysis →</Link><div className="product-proof"><span>No account</span><i/><span>No wallet</span><i/><span>Base mainnet</span></div></div></section>
<section className="product-preview-section"><div className="shell product-preview-wrap"><div className="product-preview-bar"><span>Illustrative workspace · values intentionally omitted</span><b>Evidence first · Agent explained</b></div><div className="product-preview"><aside><div className="preview-token"><div>?</div><span><b>BASE TOKEN</b><small>Example layout</small></span></div><nav><strong>Overview</strong><span>Market</span><span>Holders</span><span>Security</span><span>Social</span></nav><div className="preview-status"><i/> Research workflow</div></aside><div className="preview-main"><header><div><small>BASELENS SCORE</small><strong>--<span>/100</span></strong><em>Calculated from evidence</em></div><div className="preview-agent"><small>AGENT VERDICT</small><p>The agent explains the strongest signal, biggest risk and what evidence is still missing.</p></div></header><div className="preview-metrics"><div><span>Liquidity</span><b>--</b></div><div><span>Safety</span><b>--</b></div><div><span>Holders</span><b>--</b></div><div><span>Social</span><b>--</b></div></div><div className="preview-evidence"><div><small>STRONGEST SIGNAL</small><b>Shown from collected evidence</b></div><div><small>BIGGEST RISK</small><b>Separated from missing data</b></div><div><small>CONFIDENCE</small><b>Based on evidence coverage</b></div></div></div></div></div></section>
<section className="product-story"><div className="shell story-grid"><div className="story-heading"><span>One contract. Several checks.</span><h2>Research the token from more than one angle.</h2><p>Choose the investigation you need, or run everything together. BaseLens keeps missing data separate from actual risk.</p></div><div className="story-list"><article><span>01</span><div><h3>Market & on-chain</h3><p>Price, market cap, liquidity, trading flow, pair age and holder structure.</p></div></article><article><span>02</span><div><h3>Security</h3><p>Honeypot signals, restrictions, taxes, ownership, minting and contract verification.</p></div></article><article><span>03</span><div><h3>Social & identity</h3><p>Official website, X, Telegram, Farcaster and the social evidence available for the token.</p></div></article><article><span>04</span><div><h3>Agent interpretation</h3><p>A deterministic score first. Then the agent explains the evidence, confidence and trade-offs.</p></div></article></div></div></section>
<section className="agent-loop-section"><div className="shell agent-loop-grid"><div><span className="section-kicker">Built as an agent</span><h2>It researches before it answers.</h2></div><div className="agent-loop"><div><b>Observe</b><span>Collect evidence</span></div><i>→</i><div><b>Analyze</b><span>Normalize signals</span></div><i>→</i><div><b>Reason</b><span>Weigh trade-offs</span></div><i>→</i><div><b>Decide</b><span>Grade the profile</span></div><i>→</i><div><b>Explain</b><span>Show the evidence</span></div></div></div></section>
<section className="faq-section"><div className="shell faq-grid"><div><span className="section-kicker">Questions</span><h2>Before you use the score.</h2></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="product-final-cta"><div className="shell final-cta-inner"><div><span>BaseLens Agent</span><h2>Research the contract.<br/>Then make your own call.</h2></div><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href="/compare">Compare tokens</Link></div></div></section></main>}
