import type { Metadata } from "next";
import Link from "next/link";
const demoContract="0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4";
export const metadata:Metadata={alternates:{canonical:"/"}};
const faq=[
  ["Does a high score mean I should buy?","No. The score summarizes the evidence BaseLens could check. It does not predict returns or tell you what to buy."],
  ["What happens when data is missing?","BaseLens lowers its confidence instead of treating missing information as a problem with the token."],
  ["What does BaseLens check?","Market activity, liquidity, holder distribution, contract controls, recent trading and other evidence that is available for the token."],
  ["Can I compare tokens on different networks?","Yes. BaseLens is being built for supported EVM networks, so tokens do not have to be on the same chain to be compared."],
  ["Which networks are supported?","BaseLens supports major EVM networks including Ethereum, Base, Arbitrum, Optimism, Polygon, BNB Chain, Avalanche, Linea, Scroll, zkSync Era, Blast and Mantle."],
] as const;
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};
export default function Home(){return <main id="main-content" className="product-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/><section className="product-hero"><div className="product-grid" aria-hidden="true"/><div className="shell product-hero-inner"><div className="hero-copy"><div className="product-eyebrow"><span/> EVM token research agent</div><h1>Know what you’re looking at <em>before you trade.</em></h1><p>Paste a token contract. BaseLens researches the token, the project behind it, its market, holders and contract risks, then explains what matters in plain language.</p><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href={`/analyze/${demoContract}?chain=base`}>Open TOSHI demo</Link></div><p className="product-context">Research tokens across supported EVM networks. No wallet connection required.</p></div><div className="hero-research-panel" aria-label="BaseLens research flow preview"><div className="hero-panel-head"><span>Research path</span><b>Evidence first</b></div><ol><li><span>01</span><div><b>Contract</b><small>Confirm the token and selected network</small></div><i>Ready</i></li><li><span>02</span><div><b>Market</b><small>Price, liquidity, volume and pair activity</small></div><i>Live</i></li><li><span>03</span><div><b>Holders</b><small>Check how much of the supply large wallets control</small></div><i>Check</i></li><li><span>04</span><div><b>Contract</b><small>Look for restrictions, taxes and owner controls</small></div><i>Check</i></li><li className="agent-row"><span>05</span><div><b>Agent</b><small>Explain what looks good, what looks risky and what is unknown</small></div><i>Explain</i></li></ol><Link href={`/analyze/${demoContract}?chain=base`}>View a completed analysis <span>→</span></Link></div></div></section>
<section className="product-preview-section"><div className="shell product-preview-wrap"><div className="product-preview-bar"><span>Research workspace</span><b>Missing information is not treated as a detected risk</b></div><div className="product-preview"><aside><div className="preview-token"><div>?</div><span><b>EVM TOKEN</b><small>Research workspace</small></span></div><nav><strong>Overview</strong><span>Market</span><span>Holders</span><span>Contract</span></nav><div className="preview-status"><i/> Research in progress</div></aside><div className="preview-main"><header><div><small>BASELENS SCORE</small><strong>--<span>/100</span></strong><em>Calculated from available evidence</em></div><div className="preview-agent"><small>AGENT SUMMARY</small><p>A short explanation of the strongest point, the main concern and anything BaseLens could not verify.</p></div></header><div className="preview-metrics"><div><span>Liquidity</span><b>--</b></div><div><span>Contract</span><b>--</b></div><div><span>Holders</span><b>--</b></div><div><span>Trading</span><b>--</b></div></div><div className="preview-evidence"><div><small>STRONGEST POINT</small><b>Based on the checks that completed</b></div><div><small>MAIN CONCERN</small><b>A detected issue, not a guess</b></div><div><small>CONFIDENCE</small><b>Higher when more checks have reliable data</b></div></div></div></div></div></section>
<section className="product-story"><div className="shell story-grid"><div className="story-heading"><span>One contract. A clearer picture.</span><h2>Check the token, not the hype.</h2><p>BaseLens keeps the numbers separate from the AI explanation, so you can see what the conclusion is based on.</p></div><div className="story-list"><article><span>01</span><div><h3>Market & liquidity</h3><p>See the price, market cap, available trading liquidity, recent volume and trading activity.</p></div></article><article><span>02</span><div><h3>Holder structure</h3><p>See whether a small number of large wallets control a large share of the token when holder data is available.</p></div></article><article><span>03</span><div><h3>Contract checks</h3><p>Look for selling restrictions, unusual taxes, owner controls, minting and contract verification.</p></div></article><article><span>04</span><div><h3>Plain-language explanation</h3><p>The agent turns the checks into a short explanation and tells you when there is not enough information to make a claim.</p></div></article></div></div></section>
<section className="agent-loop-section"><div className="shell agent-loop-grid"><div><span className="section-kicker">How the agent works</span><h2>It checks first, then explains.</h2><p>The AI does not make up token statistics. BaseLens collects and normalizes the data first, then gives the agent the results to explain.</p></div><div className="agent-loop"><div><b>Collect</b><span>Gather token data</span></div><i>→</i><div><b>Check</b><span>Compare the signals</span></div><i>→</i><div><b>Score</b><span>Calculate the result</span></div><i>→</i><div><b>Explain</b><span>Use plain language</span></div></div></div></section>
<section id="faq" className="faq-section"><div className="shell faq-grid"><div><span className="section-kicker">FAQ</span><h2>A few things to know.</h2><p className="faq-intro">BaseLens is a research tool. The score is a summary of available evidence, not a prediction.</p></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="product-final-cta"><div className="shell final-cta-inner"><div><span>BaseLens</span><h2>Paste a contract.<br/>See what the data says.</h2></div><div className="product-actions"><Link className="product-primary" href="/analyze">Analyze a token <span>→</span></Link><Link className="product-secondary" href="/compare">Compare tokens</Link></div></div></section></main>}
