"use client";
import { useState } from "react";
import type { FullAnalysis } from "@/lib/types";
import { fmtMoney } from "@/lib/utils";

export function CompareClient(){
  const [inputs,setInputs]=useState(["",""]),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[err,setErr]=useState("");
  async function go(){setBusy(true);setErr("");setData(null);try{const r=await fetch("/api/compare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contracts:inputs.filter(Boolean)})}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){setErr(e instanceof Error?e.message:"Comparison failed")}finally{setBusy(false)}}
  return <div className="shell"><div className="pagehead"><div className="eyebrow">Same pipeline · relative evidence</div><h1>Which token has the strongest profile?</h1><p className="section-copy">Compare 2 to 5 Base contracts across market health, liquidity, holders, security, social evidence and momentum. This ranks the available evidence, not future returns.</p></div><div className="compare-inputs">{inputs.map((v,i)=><input key={i} className="input" aria-label={`Token ${i+1} contract`} placeholder={`Token ${i+1} · 0x…`} value={v} onChange={e=>setInputs(a=>a.map((x,j)=>j===i?e.target.value:x))}/>)}</div><div className="actions">{inputs.length<5&&<button className="btn ghost" onClick={()=>setInputs(a=>[...a,""])}>+ Add token</button>}{inputs.length>2&&<button className="btn ghost" onClick={()=>setInputs(a=>a.slice(0,-1))}>Remove</button>}<button className="btn blue" disabled={busy} onClick={go}>{busy?"Researching profiles…":"Compare tokens"}</button></div>{err&&<div className="error">{err}</div>}{busy&&<div className="loading"><span className="pulse"/> Running the same research pipeline across every valid contract…</div>}{data&&<Results x={data}/>}</div>
}

function Results({x}:{x:any}){
  const comp=x.comparison,items=x.items as FullAnalysis[];
  const agentOrder = new Map<string,number>((comp?.ranking||[]).map((r:any)=>[String(r.contract).toLowerCase(),Number(r.rank)]));
  const ordered=[...items].sort((a,b)=>{const ar=agentOrder.get(a.data.contract.toLowerCase()),br=agentOrder.get(b.data.contract.toLowerCase());if(ar&&br)return ar-br;if(ar)return -1;if(br)return 1;return b.data.scores.overall-a.data.scores.overall});
  const winner=ordered[0];
  return <div className="results">{winner&&<section className="panel winner"><div className="panel-body"><div className="eyebrow">Agent’s Strongest Profile</div><h2>{winner.data.token.name||winner.data.token.symbol} · {winner.data.scores.overall}/100</h2><p>{comp?.winnerExplanation||"Strongest deterministic overall profile among the valid tokens compared."}</p><small>Relative evidence ranking only. Not a prediction or buy recommendation.</small></div></section>}<section className="panel top"><div className="tablewrap"><table className="table"><thead><tr><th>Rank</th><th>Token</th><th>Market cap</th><th>Liquidity</th><th>24h volume</th><th>Holders</th><th>Safety</th><th>Social</th><th>Overall</th><th>Confidence</th></tr></thead><tbody>{ordered.map((it,i)=>{const a=it.data;return <tr key={a.contract}><td>#{i+1}</td><td><b>{a.token.symbol||a.token.name}</b></td><td>{fmtMoney(a.market.marketCap)}</td><td>{fmtMoney(a.liquidity.usd)}</td><td>{fmtMoney(a.trading.volume24h)}</td><td>{a.scores.holderHealth}</td><td>{a.scores.contractSafety}</td><td>{a.scores.socialPresence}</td><td><b>{a.scores.overall}</b></td><td>{a.confidence.score}%</td></tr>})}</tbody></table></div></section>{comp&&<section className="panel top"><div className="panel-head"><b>Why the profiles ranked this way</b></div><div className="panel-body">{[...comp.ranking].sort((a:any,b:any)=>a.rank-b.rank).map((r:any)=><div className="rank" key={r.contract}><b>#{r.rank}</b><p>{r.explanation}</p></div>)}</div></section>}</div>
}
